# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    target-branch: "v0.0.1.8-pw3" # 当前开发分支，切换开发分支时同步更新；仅在默认分支上的本文件生效
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    target-branch: "v0.0.1.8-pw3" # 当前开发分支，切换开发分支时同步更新
    schedule:
      interval: "weekly"
